version: "3.7"
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      - TZ=Asia/Bangkok

  kafka:
    image: debezium/kafka:1.4
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - TZ=Asia/Bangkok
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER=kafka:9092

  connect:
    image: debezium/connect:1.4
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./docker/kafka_connect/kafka-connect-jdbc:/kafka/connect/kafka-connect-jdbc
    depends_on:
      - zookeeper
      - kafka
      - mariadb
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  mariadb:
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/database/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=debezium

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ=Asia/Bangkok
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - TZ=Asia/Bangkok
      - ELASTICSEARCH_URL=http://elasticsearch:9200
